### ISSUE TITLE
hi~ 不好意思以这样的方式打扰了

### ISSUE THREAD

**Issue by welann** [RayKr/amb_docs#1]
事情是这样子的，我的导师给我发了这个项目的链接 https://github.com/DIG-Beihang/AISafety
我看到这个项目已经一年半没维护了，虽然改一改还能运行，但是有点担心它是不是有什么明显的缺陷（你们还在使用嘛？
（不好意思我的水平很低，经验也不足，所以看不出来有什么缺陷

~然后就在Contributor里找到只有你一直在活跃，所以就发了这个issue~

期待回复❤️

**Comment by raykr** [comment]
目前是别的组的同学在维护，应该没有大问题，平台也在正常用的，可以按你的需求自行修改。

**Comment by welann** [comment]
好的，谢谢回复❤️
